// CLI Project Report types - mirrors the agent.ts types from forvibeapp

export type AppType =
  | "game"
  | "health"
  | "finance"
  | "ecommerce"
  | "education"
  | "media"
  | "utility"
  | "social"
  | "other";

export type DataCollectedType =
  | "name_email"
  | "profile_photo"
  | "location"
  | "device_info"
  | "health_data"
  | "financial_info"
  | "usage_analytics"
  | "contacts"
  | "photos_media"
  | "biometric_data";

export type AdvertisingType = "personalized" | "non_personalized" | "none";

export interface ThirdPartyServices {
  analytics: string[];
  payment: string[];
  auth: string[];
  ads: string[];
  cloud: string[];
  ai: string[];
  social: string[];
  other: string[];
}

export interface BusinessModelDetails {
  model: "free" | "paid" | "freemium";
  purchase_type: "one_time" | "subscription" | "both" | "none";
  has_trial?: boolean;
  trial_duration?: string;
  has_auto_renewal?: boolean;
  has_refund_policy?: boolean;
  refund_period_days?: number;
}

export interface DetectedSDK {
  name: string;
  category: string;
  collects: string[];
}

export interface ASOStoreContent {
  app_name: string;         // max 30 chars
  subtitle: string;         // max 30 chars
  description: string;      // max 4000 chars
  keywords: string;         // max 100 chars, comma-separated, no spaces
  promotional_text: string; // max 170 chars
  whats_new: string;        // max 170 chars
}

export interface ASOPlayStoreContent {
  title: string;              // max 30 chars
  short_description: string;  // max 80 chars
  description: string;        // max 4000 chars
  whats_new: string;          // max 500 chars
}

export interface ASOContent {
  appstore?: ASOStoreContent;
  playstore?: ASOPlayStoreContent;
}

// App asset types for CLI-extracted visual assets
export type CLIAssetType =
  | "app_icon"
  | "screenshot"
  | "splash_screen"
  | "feature_graphic"
  | "promotional_image";

export interface CLIAppAsset {
  asset_type: CLIAssetType;
  file_name: string;
  mime_type: string;        // "image/png" | "image/jpeg" | "image/webp"
  // Either base64_data (legacy) OR storage_bucket+storage_path (new, direct upload).
  base64_data?: string;
  storage_bucket?: string;
  storage_path?: string;
  width: number | null;
  height: number | null;
  source_path: string;
}

// Play Store content declarations (for Play Console setup)
export interface PlayStoreDeclarations {
  // App Access: does the app require login or special access?
  app_access: "unrestricted" | "restricted_login" | "restricted_other";
  app_access_instructions?: string; // How to access restricted features

  // Ads: does the app contain ads?
  contains_ads: boolean;

  // Target Audience: age groups the app targets
  target_age_group: "all_ages" | "older_users_only" | "mixed";
  is_appeal_to_children: boolean; // Does the app appeal to children even if not targeted?

  // Government Apps
  is_government_app: boolean;

  // Financial Features
  has_financial_features: boolean;
  financial_features_details?: string; // e.g., "In-app purchases, digital wallet"

  // Health Apps (HCSA - Health Claims & Safety Apps)
  is_health_app: boolean;
  health_app_details?: string; // e.g., "Fitness tracking, calorie counter"
}

export interface CLIProjectReport {
  // Basic identification
  app_name: string;
  bundle_id: string;
  description: string;
  platforms: ("ios" | "android")[];
  tech_stack: string;
  min_os_versions: { ios?: string; android?: string };
  version: string;

  // Legal/Privacy
  app_type: AppType;
  is_for_children: boolean;
  data_collected: DataCollectedType[];
  advertising_type: AdvertisingType;
  third_party_services: ThirdPartyServices;
  business_model: BusinessModelDetails;

  // ASO
  app_category_suggestion: string;
  key_features: string[];
  target_audience: string;
  unique_selling_points: string[];

  // ASO content (generated by CLI)
  aso_content?: ASOContent;

  // Landing page / branding
  primary_color: string;
  secondary_color: string;
  brand_colors?: string[];
  detected_fonts?: string[];
  app_icon_base64: string | null;

  // App assets (extracted from project)
  app_assets?: CLIAppAsset[];

  // App Review Information
  sign_in_required?: boolean;
  test_account?: { email: string; password: string };
  review_contact?: { first_name: string; last_name: string; email: string; phone: string };
  review_notes?: string;

  // Play Store Declarations (for Play Console content setup)
  play_store_declarations?: PlayStoreDeclarations;

  // Raw data
  detected_sdks: DetectedSDK[];
  readme_content: string | null;
  config_files_found: string[];
}

// Tech stack detection result
export type TechStack =
  | "swift"
  | "flutter"
  | "react-native"
  | "expo"
  | "kotlin"
  | "capacitor"
  | "dotnet-maui"
  | "unknown";

export interface TechStackResult {
  stack: TechStack;
  label: string;
  platforms: ("ios" | "android")[];
  configFiles: string[];
}

// Config parsing result
export interface ParsedConfig {
  app_name: string | null;
  bundle_id: string | null;
  version: string | null;
  min_ios_version: string | null;
  min_android_sdk: string | null;
  description: string | null;
}

// Branding result
export interface BrandingResult {
  primary_color: string | null;
  secondary_color: string | null;
  app_icon_base64: string | null;
  app_icon_path: string | null;
  brand_colors: string[];
}

// SDK scan result
export interface SDKScanResult {
  detected_sdks: DetectedSDK[];
  data_collected: DataCollectedType[];
  advertising_type: AdvertisingType;
  third_party_services: ThirdPartyServices;
  has_iap: boolean;
}
